wwus_article_homepage:
    path:     /article
    defaults:  
        _controller: WwusArticleBundle:Article:index 

wwus_tags_index:
    path:    /article/tags 
    defaults:
        _controller: WwusArticleBundle:Tags:index

wwus_tags_new:
    path:    /article/tags/new 
    defaults:
        _controller: WwusArticleBundle:Tags:new 