wwus_article_homepage:
    path:     /article
    defaults:  
        _controller: WwusArticleBundle:Article:index 

wwus_article_new:
    path:    /article/new
    defaults:
        _controller: WwusArticleBundle:Article:new

wwus_article_brouillons:
    path:    /article/brouillons 
    defaults:
        _controller: WwusArticleBundle:Article:brouillons

wwus_tags_index:
    path:    /article/tags 
    defaults:
        _controller: WwusArticleBundle:Tags:index

wwus_tags_new:
    path:    /article/tags/new 
    defaults:
        _controller: WwusArticleBundle:Tags:new 

wwus_tags_modif:
    path:    /article/tags/modif/{id}
    defaults:
        _controller: WwusArticleBundle:Tags:modif

wwus_tags_supp:
    path:    /article/tags/supp/{id}
    defaults:
        _controller: WwusArticleBundle:Tags:supp 