<?php

namespace Wwus\ExerciceBundle\Repository;

/**
 * Advert_skillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Advert_skillRepository extends \Doctrine\ORM\EntityRepository
{
}
