<?php

namespace Wwus\ArticleBundle\Repository;

/**
 * Article_tagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Article_tagRepository extends \Doctrine\ORM\EntityRepository
{
}
