wwus_article:
    resource: "@WwusArticleBundle/Resources/config/routing.yml"
    prefix:   /

wwus_admin:
    resource: "@WwusAdminBundle/Resources/config/routing.yml"
    prefix:   /

wwus_blog:
    resource: "@WwusBlogBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
